[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = { version = "0.9.0", default-features = false, features = ["atty", "termcolor"] }
futures-util = "0.3.15"
indoc = "1.0.3"
log = { version = "0.4.14", features = ["release_max_level_info"] }
reqwest = { version = "0.11.4", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.8.2", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
twilight-embed-builder = "0.5.2"
twilight-gateway = { version = "0.5.3", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.5.6", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.5.3"
twitch-irc = { version = "3.0.1", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }

[dev-dependencies]
pretty_assertions = "0.7.2"

[profile.release]
lto = true
