[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.55"
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
docsearch = "0.3.0"
futures-util = "0.3.21"
indoc = "1.0.4"
lru_time_cache = "0.11.11"
once_cell = "1.9.0"
reqwest = { version = "0.11.9", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
twilight-embed-builder = "0.9.0"
twilight-gateway = { version = "0.9.1", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.9.1", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.9.2"
twitch-irc = { version = "3.0.1", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }
unidirs = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.1.0"

[profile.release]
lto = true
