[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
cienli = { version = "0.3.1", default-features = false, features = ["rot"] }
docsearch = "0.3.2"
futures-util = "0.3.25"
indexmap = { version = "1.9.1", features = ["serde-1"] }
indoc = "1.0.7"
lru_time_cache = "0.11.11"
once_cell = "1.16.0"
reqwest = { version = "0.11.12", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.147", features = ["derive", "rc"] }
serde_json = "1.0.87"
time = { version = "0.3.16", features = ["formatting", "macros", "parsing", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.21.2", features = ["fs", "macros", "rt", "sync"] }
tokio-shutdown = "0.1.3"
toml = "0.5.9"
tracing = "0.1.37"
tracing-quiver = { git = "https://github.com/dnaka91/archer.git" }
tracing-subscriber = "0.3.16"
twilight-gateway = { version = "0.13.3", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.13.3", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.13.7"
twilight-util = { version = "0.13.3", features = ["builder"] }
twitch-irc = { version = "5.0.0", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }
unidirs = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.release]
lto = true
strip = true
