[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.58"
async-trait = "0.1.56"
cienli = { version = "0.3.1", default-features = false, features = ["rot"] }
docsearch = "0.3.2"
futures-util = "0.3.21"
indexmap = { version = "1.9.1", features = ["serde-1"] }
indoc = "1.0.6"
lru_time_cache = "0.11.11"
once_cell = "1.13.0"
reqwest = { version = "0.11.11", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.140", features = ["derive", "rc"] }
serde_json = "1.0.82"
time = { version = "0.3.11", features = ["formatting", "macros", "parsing", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.20.1", features = ["fs", "macros", "rt", "sync"] }
tokio-shutdown = "0.1.2"
toml = "0.5.9"
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
twilight-gateway = { version = "0.12.1", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.12.1", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.12.2"
twilight-util = { version = "0.12.1", features = ["builder"] }
twitch-irc = { version = "4.0.0", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }
unidirs = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.2.1"

[profile.release]
lto = true
strip = true
