[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.91"
docsearch = "0.3.5"
futures-util = { version = "0.3.31", features = ["sink"] }
indexmap = { version = "2.6.0", features = ["serde"] }
indoc = "2.0.5"
lru_time_cache = "0.11.11"
once_cell = "1.20.2"
poise = "0.6.1"
reqwest = { version = "0.12.8", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.213", features = ["derive", "rc"] }
serde_json = "1.0.132"
time = { version = "0.3.36", features = ["formatting", "macros", "parsing", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.41.0", features = ["fs", "macros", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.4"
tokio-tungstenite = { version = "0.24.0", features = ["rustls-tls-webpki-roots"] }
toml = "0.8.19"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
twitch_api = { version = "0.7.0-rc.8", features = ["eventsub", "helix", "reqwest"] }
unidirs = "0.1.1"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
lto = "thin"
strip = true
