[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
rust-version = "1.56"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
docsearch = "0.2.0"
futures-util = "0.3.19"
indoc = "1.0.3"
lru_time_cache = "0.11.11"
once_cell = "1.9.0"
reqwest = { version = "0.11.9", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
tokio = { version = "1.15.0", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
twilight-embed-builder = "0.8.0"
twilight-gateway = { version = "0.8.4", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.8.4", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.8.4"
twitch-irc = { version = "3.0.1", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }

[dev-dependencies]
pretty_assertions = "1.0.0"

[profile.release]
lto = true
