[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.90"
async-trait = "0.1.83"
docsearch = "0.3.5"
indexmap = { version = "2.6.0", features = ["serde"] }
indoc = "2.0.5"
lru_time_cache = "0.11.11"
once_cell = "1.20.2"
poise = "0.6.1"
reqwest = { version = "0.11.27", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_json = "1.0.131"
time = { version = "0.3.36", features = ["formatting", "macros", "parsing", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.40.0", features = ["fs", "macros", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.4"
toml = "0.8.19"
tracing = "0.1.40"
tracing-archer = { git = "https://github.com/dnaka91/archer.git" }
tracing-subscriber = "0.3.18"
twitch-irc = { version = "5.0.1", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }
unidirs = "0.1.1"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
lto = "thin"
strip = true
