[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = { version = "0.8.3", default-features = false, features = ["atty", "termcolor"] }
futures-util = "0.3.15"
indoc = "1.0.3"
log = { version = "0.4.14", features = ["release_max_level_info"] }
reqwest = { version = "0.11.3", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.6.1", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
twilight-embed-builder = "0.4.1"
twilight-gateway = { version = "0.4.1", default-features = false, features = ["rustls-webpki-roots", "stock-zlib"] }
twilight-http = { version = "0.4.2", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.4.2"
twitch-irc = "2.2.0"

[dev-dependencies]
pretty_assertions = "0.7.2"

[profile.release]
lto = true
