[package]
name = "togglebot"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
async-trait = "0.1.51"
chrono = { version = "0.4.19", features = ["serde"] }
docsearch = "0.2.0"
env_logger = { version = "0.9.0", default-features = false, features = ["atty", "termcolor"] }
futures-util = "0.3.17"
indoc = "1.0.3"
log = { version = "0.4.14", features = ["release_max_level_info"] }
lru_time_cache = "0.11.11"
once_cell = "1.8.0"
reqwest = { version = "0.11.4", default-features = false, features = ["gzip", "json", "rustls-tls"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
tokio = { version = "1.11.0", features = ["fs", "macros", "rt", "signal", "sync"] }
toml = "0.5.8"
twilight-embed-builder = "0.6.0"
twilight-gateway = { version = "0.6.2", default-features = false, features = ["rustls-webpki-roots", "zlib-stock"] }
twilight-http = { version = "0.6.3", default-features = false, features = ["rustls-webpki-roots"] }
twilight-model = "0.6.2"
twitch-irc = { version = "3.0.1", default-features = false, features = ["transport-tcp-rustls-webpki-roots"] }

[dev-dependencies]
pretty_assertions = "0.7.2"

[profile.release]
lto = true
