[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
]
exceptions = [
    { crate = "ring", allow = ["OpenSSL"] },
    { crate = "togglebot", allow = ["AGPL-3.0"] },
    { crate = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    "base64@0.21",
    "bitflags@1",
    "hashbrown@0.14",
    "http@0.2",
    "http-body@0.4",
    "hyper@0.14",
    "hyper-rustls@0.24",
    "reqwest@0.11",
    "rustls@0.21",
    "rustls@0.22",
    "rustls-pemfile@1",
    "rustls-webpki@0.101",
    "syn@1",
    "sync_wrapper@0.1",
    "tokio-rustls@0.24",
    "tokio-rustls@0.25",
    "tokio-tungstenite@0.21",
    "tungstenite@0.21",
    "wasi@0.11",
    "webpki-roots@0.25",
]
skip-tree = [
    { crate = "windows-sys@0.48", depth = 3 },
    { crate = "windows-sys@0.52", depth = 3 },
]
