[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
]

[advisories]
ignore = ["RUSTSEC-2024-0388"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

[licenses.private]
ignore = true

[bans]
skip = [
    "base64@0.21",
    "getrandom@0.2",
    "hashbrown@0.14",
    "http@0.2",
    "http-body@0.4",
    "hyper@0.14",
    "hyper-rustls@0.24",
    "reqwest@0.11",
    "rustls@0.21",
    "rustls@0.22",
    "rustls-pemfile@1",
    "rustls-webpki@0.101",
    "rustls-webpki@0.102",
    "syn@1",
    "sync_wrapper@0.1",
    "tokio-rustls@0.24",
    "tokio-rustls@0.25",
    "tokio-tungstenite@0.21",
    "tower@0.4",
    "tungstenite@0.21",
    "webpki-roots@0.25",
]
skip-tree = [
    { crate = "rand@0.8", depth = 2 },
    { crate = "thiserror@1", depth = 2 },
]
