[advisories]
version = 2

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OpenSSL",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "togglebot", version = "*" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "base64", version = "0.21" },
    { name = "bitflags", version = "1" },
    { name = "rustls", version = "0.22" },
    { name = "rustls-webpki", version = "0.101" },
    { name = "syn", version = "1" },
    { name = "wasi", version = "0.11" },
    { name = "winnow", version = "0.5" },
]
skip-tree = [
    { name = "twitch-irc", version = "5", depth = 2 },
    { name = "windows-sys", version = "0.48", depth = 3 },
]

[sources]
allow-git = [
    "https://github.com/dnaka91/archer.git",
]
