[advisories]
ignore = [
    "RUSTSEC-2020-0071",
]

[licenses]
allow = [
    "BSD-2-Clause",
    "CC0-1.0",
    "MPL-2.0",
    "OpenSSL",
]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "togglebot", version = "*" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident", version = "*" },
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "base64", version = "=0.13.1" },
    { name = "hashbrown", version = "=0.12.3" },
    { name = "hyper-rustls", version = "=0.23.2" },
    { name = "indexmap", version = "=1.9.3" },
    { name = "miniz_oxide", version = "=0.6.2" },
    { name = "rustls", version = "=0.20.8" },
    { name = "socket2", version = "=0.4.9" },
    { name = "syn", version = "=1.0.109" },
    { name = "time", version = "=0.1.45" },
    { name = "tokio-rustls", version = "=0.23.4" },
    { name = "wasi", version = "=0.11.0" },
]

[sources]
allow-git = [
    "https://github.com/dnaka91/archer.git",
]
